### ISSUE TITLE
Compiling Coffee on publish

### ISSUE THREAD

**Issue by mildsunrise** [techpines/asset-rack#30]
Instead of going ahead with a PR, I decided to ask first.

A typical convention found in many modules,
is to put the coffee scripts in `src` (since they have
to be compiled), and then add to `package.json`:

```
  "scripts": {
    "publish": "coffee -o lib/ -c src/"
  }
```

And have `coffee-script` be a `devDependencies` entry.

That way, files get transparently compiled to `lib` in the
final published archive, among with the original CoffeeScript
files. It makes things simpler for anyone (no `switch`, no
run-time compiling, no `coffee` when not needed, etc.)

Would you agree to do this in `asset-rack`?

**Comment by techpines** [comment]
Here are the problems I see with that pattern:
- It adds a "build" step to the dev process
- It puts compiled code in the repo
- Violates DRY
- Addresses theoretical vs actual problems

If you don't look at the code, I don't think you would ever know the difference.

The only thing I worry about with my current pattern is if it actually breaks someone, because of coffeescript version conflicts.

I much favor simpler/cleaner dev cycles to minimal compile time performance gains.

**Comment by mwawrusch** [comment]
This is how we do it in production on multiple apps and ~50 modules for more than a year now and this seems to be the most stable way of doing it. Here is an excerpt from our package.jsons:

Note that we do not reference the global coffeescript compiler, if available, but a locally installed one through dev dependencies. That is very important, as Coffeescript has introduced minor changes over time that would cause compilation to fail in some instances.

Key here is:
- Do not fail because of different versions of compilers
- Make it convenient for both Coffeescript and Javaascript developers.
- Be pragmatic.
  
  "scripts": {
    "prepublish" : "node_modules/.bin/coffee -c -o lib src",
    "watch" : "node_modules/.bin/coffee -c -w  -o lib src",
    "test": "node_modules/.bin/coffee -c -o lib src;NODE_ENV=test node_modules/.bin/mocha --timeout 10000 -R spec test/_-test.coffee",
    "test-xunit": "node_modules/.bin/coffee -c -o lib src;NODE_ENV=test node_modules/.bin/mocha --timeout 10000 -C -R xunit test/_-test.coffee",
    "docs": "node_modules/.bin/codo -i ./src -o ./doc",
    "t": "node_modules/.bin/coffee -c -o lib src;NODE_ENV=test node_modules/.bin/mocha --timeout 10000 -R dot test/store-style-event-like-methods-unlike-test.coffee"
  
  },
  "engines": {
    "node": ">=0.8.0"
  },
  "dependencies": {
  .......
  },
  "devDependencies": {
  ...
  "coffee-script" : "1.4.0", 
  "codo": "1.5.4"
  },

**Comment by techpines** [comment]
I have been using just-in-time compilation for all my production apps, and I haven't run into any issues yet.

However, I appreciate the coffeescript version concern.  I think that is a valid shortcoming with my current setup.

I am very big on simplicity, and anything that simplifies/quickens dev cycles means better code at the end of the day, which is why I'm averse to adding a build step, and cluttering the repo with compiled code.  

Ideally, I would keep my current setup, and modify it so that compilation of the code always occurs with the same version of coffeescript.  And then also make sure that it didn't conflict with any other runtime coffeescript versions. This would solve what I see as being the main hangup with runtime compilation.  Because I totally get the concept of not wanting to have to track down some crazy coffescript runtime version bug. 

Let me think about it.

**Comment by techpines** [comment]
Alright I did it!  There's no compiled code in the repo, but if you pull from npm, you'll get the compiled version.

```
npm install asset-rack@2.0.8
```

Let me know if you have any problems with that.

**Comment by techpines** [comment]
@jmendeth @mwawrusch Thanks guys for helping me see the light.  Compiling for published code is better.

**Comment by mwawrusch** [comment]
You are welcome. We all work here to make the node.js and coffeescript
ecosystem better...

**Comment by mildsunrise** [comment]
Sorry guys, in my timezone it was midnight... ;)
As you can see, the approach is DRY, transparent and doesn't add code to the repo.

> Thanks guys for helping me see the light. Compiling for published code is better.

Thank _you_ for this fantastic library! :)

---

About the setup, I think there's a much neater way than
compiling on `prepublish`, then removing on `postpublish`.
Will file a pull request soon.

Just asking, would you agree to have the Coffee under `src`? (as @mwawrusch does)
Not really necessary but contributes to making things simpler, especially in the NPM package.
