### ISSUE TITLE
Detect asset change?

### ISSUE THREAD

**Issue by drozzy** [techpines/asset-rack#41]
Hi (again :-),
Could you give me a tip on how I could implement a change detection of an asset?

Let's say I modify the `livescript` source, I want the javascript to be automatically regenerated next time page is reloaded (at least for development).

If it's not possible - it's no biggy, as Livescript interpreter has a "watch" feature - so I could run that during development - but would be nice to have everything in one place.

**Comment by techpines** [comment]
I'm thinking about maybe moving something like this into core, but here is a way to do it:

``` js
var assets = new LivescriptAsset(...);
require("fs-watch-tree").watchTree(__dirname, function() {
    assets = new LivescriptAsset(...);
});
app.use(assets);
```

Which uses a nodejs library called "fs-watch-tree", which is based on nodejs `fs.watch`, which can pickup changes in files.

**Comment by drozzy** [comment]
Wow, that is pretty sweet! Thanks a bunch.
So this is for the whole dir - not just one file?
Also would be nice to hide this front end user... Anyways I'll check it out tomorrow.

**Comment by techpines** [comment]
For a single file you can use `fs.watch`:

http://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener

But watching your whole project directory might be simpler if you have a bunch of files you want to watch.

**Comment by johnrobertfitz** [comment]
I ran into some problems trying to do this - was able to use fs.watch to monitor a directory for changes and rebuild the sprite, but I couldn't get the middleware working. Jade kept using the original asset.tag/asset.url locations. Any additional app.use(new_assets) just pushed to the end of the middleware stack and had no effect.

Did anyone get this working successfully?

**Comment by techpines** [comment]
What did your code look like?

**Comment by johnrobertfitz** [comment]
I created a test repo here with a hacky version:
https://github.com/johnrobertfitz/testing-asset-rack-watch

I can get the global assets object to show the correct url, but the object passed to the views is stale.

Run app, http://127.0.0.1:3000. App & jade assets.url locations should be the same at the start, make a small change to the javascripts/main.js file, watch console for the regenerating message & location.

On next fresh of page, the app assets is updated but jade still pulls the old url.

Note: It calls app.use(assets) multiple on every regenerate - this just pushes to the middleware stack - when really we want to update the original.

**Comment by noc7c9** [comment]
Try this

``` js
var assets = new Asset(...);
fs.watch(..., function() {
    assets = new Asset(...);
});

app.use(function () { // the proxy
  return assets.handle.apply(assets, arguments);
});
app.use(app.router); // this must come AFTER the proxy
```

Basically it uses a proxy middleware that lets whatever `Asset` instance that is referenced by the `assets` variable **at the time of the request** to handle the actual request.

@techpines 
I strongly suspect a more elegant approach would require significant changes to the `asset-rack` core since there isn't any handling of filepaths, but only the actual content.
Or alternatively each asset must implement watch functionality themselves. Perhaps another `utils` function to allow easy implementation? I personally don't like this approach though.

**Comment by techpines** [comment]
It might not be that complicated.

For assets based on directories, you could set it to watch for changes in that directory.  Then for files you could look for changes in the parent directory of the file.  That isn't perfect, but it would probably solve the 95% use case where you have an entry point Less, Stylus, or Browserify file and then you require other files from the parent directory.

So if you have a `toWatch` attribute, with a list of directories or filenames to look for, then you could respond to changes and rebuild assets accordingly.  

The code around removing the old assets and replacing them would be tricky.  You would have to reset the `rack` to `completed=false`, and then remove all assets associated with the previous asset.  You would also have to take care of the sub-assets, but if you have their parent then you should still be able to get to them.

Then after the rebuild is complete, you would have to trigger the rack back to being `completed`.

And then maybe test it somehow :)

**Comment by johnrobertfitz** [comment]
@noc7c9 
That worked great. I wrapped in a check so I only use the proxy in development mode and it covers my use case completely (development).

**Comment by noc7c9** [comment]
@johnrobertfitz glad I could help. :D

@techpines that makes sense, and if I'm not mistaken wouldn't setting `completed=false` then rerunning the `created` method be enough? The old assets would be overwritten and it would also set `completed=true` with `@emit 'created'`.
Perhaps there are some side effects I'm not realizing. If not it would simplify the implementation.

**Comment by techpines** [comment]
Yea, that part I'm not as sure about.  If you can safely call `create` twice or if you need to rebuild the asset.

I think you should be able to just call `create` and be done with it.

**Comment by techpines** [comment]
Actually, I'm less sure about that.  The sub-assets would need to be replaced.  However, maybe it's still doable.  But I really like the idea of calling create twice.

Ideally, I'd really like to be able to do this:

```
asset.recreate()
```

I make the asset recreate itself and automatically halt any `rack`s that it might be in.

**Comment by noc7c9** [comment]
Halt the `rack`? I'm not completely sure what you mean but won't setting `complete=false` do that?
according to [rack.coffee#L62](https://github.com/techpines/asset-rack/blob/master/lib/rack.coffee#L62) and [asset.coffee#L87](https://github.com/techpines/asset-rack/blob/master/lib/asset.coffee#L87) setting `complete=false` would make any `Rack` or `Asset` wait until building completes before responding to any new requests.
A way to handle sub-assets is `@assets = [] if @assets?`

Regardless it would be best just to implement this and make a few tests to ensure correct functionality.

Also should this be on by default? Perhaps turn on unless in `production`?

**Comment by jeanlauliac** [comment]
Asset re-creation on change is a feature I'm looking for too, in a similar way to connect-assets.

An important point is that it should take into consideration the dependencies of the assets too: if a snocket coffee file A `#= include` another one B for instance, A should be recreated whenever B changes. Even if B itself is not an asset. Snockets provides the dep graph, but I'm not sure about Stylus & others (if we do an `@import 'B.styl'` from A.styl for example).

Plus, instead of watching files, it could be handled the same way as connect-assets; storing the max timestamp of the asset and its dependencies. If the asset or a dep timestamp gets greater then the stored one, then it could trigger re-creation. This may be done in the `Asset.tag` call for each asset since the returned url would be different (different hash).

**Comment by techpines** [comment]
@undashes I guess it's not totally clear to me why you wouldn't use `watch`.

This is a top priority.

I think for any asset that we can't get the dependency graph easily, (meaning without parsing it, and following it ourselves) that for those assets we would just default to watching the parent directory of the file.  Which isn't perfect, but I think that fits the 95% use case.

In the following example if the asset filename was `main.styl`, if you watch it's parent directory `styles`, most likely that is where all of it's dependencies will live based on how most people structure projects.

```
styles/
    main.styl
    components.styl
    other/
         images.styl
         headers.styl
```

**Comment by jeanlauliac** [comment]
The fact is, I'm trying to migrate from connect-assets to asset-rack to see what benefits we could get with the CDN features, etc., and the project I'm working on contains a lot of existing "front-end" `coffee` and `styl`, used by different parts of the whole application. So I'm not using directly StylusAsset of SnocketAsset, but DynamicAssets instead. This raise some issues.

First, it tries to compile every file, including the ones that are meant to be included only (but we don't need them, especially on the CDN, since there're going to be concat to the parent files): this is "easily" solvable by moving all included files into a `lib` directory and connect DynamicAssets to a another, `src`, directory only. Another solution would be to manually add of the "front-end" files as assets, but this is less manageable in the long run.

Then, I can indeed watch both `lib` and `src` directory, for my `js`, `css`, plus my separate `static`, etc. I've tested it using the piece of code abovementioned with `watch` (thanks!), and **it works perfectly well**; except the fact that if I'm modifying a single little `coffee` or `styl` file for debugging, the whole tree is re-created, which is not ideal since there are a lot of them. The goal here, of course, is to take a minimum of time recompiling assets during debugging sessions.

I guess asset-rack was designed with single-page web applications in mind, so that's why my case is a bit different indeed. My envisioned structure is globally like this:

```
asset-rack/
  js/
    src/
       the files here include some from lib, and are then included by assets.tags from some jade views
    lib/
       all the included-only files
  css/
     src/
     lib/
  static/
```

The prev stucture (connect-assets) was like this:

```
assets/
  js/
    a bunch of coffee and js files
  css/
    a bunch of stylus files, some included from jade views, some not
public/
```

With file changes detection and confined asset recreation, asset-rack would be a much stronger alternative to connect-assets!

I'm currently [experimenting with making some changes](https://github.com/benbria/asset-rack) in the lib, to see what I can do for this.

**Comment by noc7c9** [comment]
The concatenation of dependencies are handled by the individual compilers, so unfortunately I doubt there's a way for `asset-rack` to recompile only the changed files unless the compiler supports it.

Of course I could be wrong. This would be a killer feature :D

**Comment by vincentwoo** [comment]
This is a major feature missing when migrating from connect-assets to asset-rack

**Comment by techpines** [comment]
I know it's coming.

I've been kind of swamped this past month.

**Comment by jeanlauliac** [comment]
By the way, to anwser @noc7c9, the way to detect dependencies is to use Scockets for coffees, and to pattern-match the `@import 'foobar'` and optionally `url(foobar)` (for images or font dependencies) for Stylus, for example. Same idea for the other kind of files (Sass, etc.). Not ideal, but working! I believe that's exactly how is doing `connect-assets`.

So to detect change, the lib just have to `stat` each file and compare the timestamp to the previous build timestamp of this specific parent (and to be even better doind a SHA-1 comparaison).

Note that dependencies would generally not be part the 'assets' themselves, only included by the assets. Additionally, a fancy feature of `connect-assets` is that is does not concatenate Coffee files in debug mode, it just replace the calling helper in the view by _several_ tags for each dependency. That's very handy to debug in browser.

**Comment by noc7c9** [comment]
I think I misunderstood you, I was stating that its not possible to compile **_only**_ changed files. Say only the dependency but not the file that includes it.

But yes that would probably work. Perhaps it might even be possible to hook into the compiling process itself and get a list of files that way (doesn't `less` provide a parse tree?). And if not we could just add that feature ourselves :D

Could you explain why you think comparing timestamps is better than `watch`? It seems like a whole lot of redundant work to me.

> Note that dependencies would generally not be part the 'assets' themselves, only included by the assets.

I don't understand what you mean by this.

**Comment by jeanlauliac** [comment]
Hmm, yea sorry my sentence was not very clear, what I meant is that the files that are included by an asset are generally not 'assets' themselves. For example, to be clear, `foobar.coffee` include (via a `# require`) another file `some-library.coffee`, then only the `foobar.coffee` have to be served (and actually sent on the CDN). This can be problematic to implement a smart behavior like in `connect-assets` where it is able to split the `<script>` HTML tag in two: one for `foobar.js` and one for `some-library.js` (rationale: it's easier for debugging).

**EDIT:** yea, I should have said: "then _generally_ only the `foobar.coffee` have to be served", of course a lib file could be, or not, an asset as well.

About the `watch`, well, the benefit of timestamp is that it's specific for each file, so we can recompile only the modified files very precisely (or, of course, the parent files that include them), not all the directory (plus I believe `watch` is not always too reliable especially on platforms like Windows, but maybe it improved since then). But, well, we can actually do the same with `watch` by recompiling only the files reported as changed.

**Comment by noc7c9** [comment]
Actually your assumption isn't always true. There is no guarantee that the included file doesn't need to be served.
Say hypothetically I use `foobar.coffee` on one page but I use `some-library.coffee` directly on another page. Therefore both files need to be served.
Stupid thing to do, but that doesn't make it impossible.

And you completely correct about `watch`. Its labeled [unstable](http://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener).
Also note that [`watchFile`](http://nodejs.org/api/fs.html#fs_fs_watchfile_filename_options_listener) uses stat polling so you can use that instead of reinventing the wheel if you go with the timestamp approach. It is however labeled as less reliable so maybe you can use it as a fallback or something?

**Comment by jeanlauliac** [comment]
Well, there is even no need to poll the file regularly, the lib just need to check the timestamp of a specific file (+deps) when it is requested via HTTP. If modified, recompile, and serve. If not, just serve the cached version.
It's just a `stat` call and I actually implemented it (a bit quick & dirty though, and ignoring deps.) for assets, for example: https://github.com/benbria/asset-rack/commit/ffe8b59da0c1fac29b193bfcced1ca89becd777e#L0R98

**Comment by noc7c9** [comment]
The code seems good except for a few things.
- `@update` should be called in the `handle` method not the `tag` method.
- consider disabling automatically if the environment is not development directly instead of `options.debug` (which isn't used by the way).
- `@filename` is not a reliable way to get what to watch, not every asset uses `@filename`. Instead you'll probably need each individual asset to specify what to watch. Perhaps a list of filenames or something? This is the way to support dependencies as well.

And many thanks for working on this much needed feature :D

**Comment by techpines** [comment]
Done.

```
asset-rack@2.2.0
```

Here's the syntax:

``` js
new LessAsset({
    watch: true
    ...
});
```

The way it works is that if `watch` is set than the asset looks at it's `toWatch` variable which is a path for either a file or directory.  If anything change it recreates the asset.

So you might be wondering how this works for the `LessAsset`, well I'm just watching the parent directory of whatever the filename is.  That's how it works for all of the assets that show up as one, even though they have other file dependencies.  So basically if all your less files aren't in the same directory tree with you entry point at the top, then watch might not work.  However, it works in all my current use cases and it was easy to implement so that's just how it will be for now.  

One improvement to this setup would be to let the user specify `toWatch` as a list of filenames and dirnames, but maybe save that til later.

Cheers!
