### ISSUE TITLE
How do I concatenate js and css files?

### ISSUE THREAD

**Issue by ragulka** [techpines/asset-rack#47]
I would like to concatenate all my javascript files into one js file and all my css files into one css file. As far as I can see, for JS I would have to use a SnocketsAsset, but for CSS there does not seem to be an equivalent (can I just use SnocketsAsset for css as well?).

However, I cannot understand how I would use SnocketsAsset to concat multiple js files. The documentation says that for `filename` I should provide "A filename or list of filenames to be executed by the browser". But when I provide an array of filenames, I get a node error: `Error: EISDIR, illegal operation on a directory`.

**Comment by techpines** [comment]
Currently, there isn't a built-in asset for vanilla CSS support.  You could convert to something like less, http://lesscss.org

And then have one file that is your entry point, like `index.less`:

``` css
@import "reset";
@import "styles";
@import "tables";
```

As for the snockets asset, I'll have to check on that functionality.  That was contributed by someone else.  But the idea there is similar:

``` js
//= require app.js
//= require models.js
```

You setup one file that is the entry point, and then it pulls in all the dependencies.  

I hope that helps.  Let me know if you have more issues.

**Comment by ragulka** [comment]
Ah thanks! I can work with that for now. 

Is it possible to create groups of assets that are only concatenated and minified in production mode?
For example, I want to add 5 different js files to the group and use a single `asset.tag()` to inject them in my jade template. If I am in development mode, I want it to actually create 5 different script tags for each of the files, but when I am in production mode, I want the files to be concatenated and minified. Possible?

**Comment by techpines** [comment]
You would have to set up a custom asset:

https://github.com/techpines/asset-rack/blob/master/lib/README.md#extending-the-asset-class

You could also look at the JavascriptAsset for sails which does mostly what you're talking about:

https://github.com/balderdashy/sails/blob/master/lib/assets.js#L20

**Comment by techpines** [comment]
If a lot of people want this functionality, I could make a custom asset for it.  I'm sure the sails guys would be happy about that.

**Comment by ragulka** [comment]
I recently discovered an alternative module, called nap. What I like about it is that it is super easy to define asset packages (exactly what I described above): https://github.com/craigspaeth/nap#1-declare-asset-packages. It currently lacks support for async preprocessors (less, etc) though.

Would you consider a configuration like that for Asset Rack? I find it much easier that doing `new rack.Asset()...` etc.

**Comment by techpines** [comment]
Just as an example, here is what you do in nap:

``` js
nap({
  assets: {
    js: {
      backbone: [
        '/app/coffeescripts/models/**/*', 
        '/app/coffeescripts/views/**/*', 
        '/app/coffeescripts/routers/**/*'
      ]
    },
    css: {
      all: [
        '/public/stylesheets/blueprint.css',
        '/app/stylesheets/**/*'
      ]
    },
    jst: {
      templates: [
        '/app/templates/index.jade',
        '/app/templates/footer.jade'
      ]
    }
  }
});
```

And if you were using asset rack with let's say browserify and less, then you would do this:

``` coffee
module.exports = new rack.AssetRack [
    new rack.LessAsset
        url: '/style.css'
        filename: "#{__dirname}/style/index.less"
    new rack.BrowserifyAsset
        url: '/app.js'
        filename: "#{__dirname}/client/app.coffee"
    new rack.JadeAsset
        url: '/templates.js'
        dirname: "#{__dirname}/templates"
]
```

So, my opinion is that the asset-rack configuration is simpler to read, and it has all of the most pertinent information about how your assets are setup.  Primarily, the urls that everything is served from, and the directory structure of the project.   And notice that this declaration is not going to grow if more files are added.  It stays this size for the entire length of the project.

To me this is a very economical and flexible way to specify a single page app.  Also, by design asset-rack does not impose a url structure or a directory structure, which is important for being non-opionated.

Also, on a final note the way that custom assets are created gives you maximum flexibility in how asssets are generated, regardless of the type image, json, javascript, templates, css.

You just have to override a create method and use the options provided to do whatever kind of setup suits you best:

``` coffee
class SomeFunAsset extends rack.Asset
    create: (options) ->
        # do some stuff
        @emit('created')
```

And then your `options` can be whatever crazy thing you want:

``` js
new SomeFunAsset({
    service: 'twitter',
    encryption: 'sha256',
    url: '/crazy-twitter-generated-asset.html'
});
```

And I guess you could argue over the correctness of this, but I believe that fundamentally asset-rack is not an asset management tool, it's a static web framework.  For that reason, I don't believe that the core framework should support the idea of anything other than serving static http resources.  All of the assets like `LessAsset`, `JadeAsset` or whatever are just nice to have, batteries included.  So they are opinionated, but that does not stop you from declaring any type of asset you like.

For the nap deal, there is nothing to stop you from making a `NapAsset`.  And if you used asset-rack you would get cdn deployments, fingerprinting, middleware and all that other good stuff for free:

``` js
new rack.NapAsset({
  js: {
      backbone: [
        '/app/coffeescripts/models/**/*', 
        '/app/coffeescripts/views/**/*', 
        '/app/coffeescripts/routers/**/*'
      ]
    },
    css: {
      all: [
        '/public/stylesheets/blueprint.css',
        '/app/stylesheets/**/*'
      ]
    },
    jst: {
      templates: [
        '/app/templates/index.jade',
        '/app/templates/footer.jade'
      ]
    }
});
```

Cheers!
