### ISSUE TITLE
assets.tag does not point to S3 resource

### ISSUE THREAD

**Issue by crisson** [techpines/asset-rack#9]
If you use this module to upload a resource to S3, subsequently calling assets.tag(resourceName) does not return a link tag with a href pointing to the s3 location where the resource was uploaded.  The href always refers to a path relative to the current hostname (i.e., `href="/css/cssResource.css"` instead of `href="https://s3.amazonaws.com/bucket_name/css/cssResource.css"`).

**Comment by techpines** [comment]
You are right.  I have an upgraded version that handles this use case.  I will make a note of it here when this is resolved.

**Comment by techpines** [comment]
Sorry that this has taken so long, but it is coming.

**Comment by crisson** [comment]
No worries, thanks for working on this great library!

**Comment by mstorus** [comment]
Does this imply that using assets.url(resourceName) **will** point to the correct s3 location? I can't figure out how to get that to work (some examples/documentation would be great). Or is it the same issue as assets.tag()

**Comment by techpines** [comment]
So here is a hack that would make assets.url work:

``` coffeescript
rack.Rack.prototype.url = (url) ->    
  for asset in @assets
    return "#{s3location}#{asset.specificUrl}" if url is asset.url
```

**Comment by techpines** [comment]
I really want to get this fixed this week, here is what I'm thinking about doing.  The idea would be that whenever you deploy assets:

``` js
assets.deploy(options)
```

A file would get written called `.rack.json`.  Which would be a mapping of urls to specific urls.   Like this:

``` js
{
   "some.html": "some-230jf29fj023fj023.html"
}
```

Then in your production environment instead of creating your assets you would do this:

``` js
assets = rack.fromFile(options)
```

And here one of the options might be `hostname`.

Then you would hook into express just the same:

``` js
app.use(assets)
```

However, all it would do is redirect you to the CDN if it got a direct request for an asset, and also add the assets object to locals for the templates.

So then you're deploy pattern would look like this:
1. Deploy static assets.
2. Deploy your code.

**Comment by techpines** [comment]
@mstorus @crisson Please let me know if that sounds logical, otherwise that will probably be how I implement it.

**Comment by mwawrusch** [comment]
Well, that has been done a lot of times.

https://github.com/pksunkara/voila
which depends on
https://github.com/nodeca/mincer

Just copy the code, it's working flawlessly :-)

The practical deployment pattern goes like this:

You host file-yourmd5.whatever

your html/css links to your CDN/....file-yourmd5.whatever

the CDN pulls from the actual webserver.

Here is  a typical manifest.json file:

'''json
{"assets":{"site.css":"site-ab002b499358beae97c9408d517066db.css","global.js":"global-d7cf3c1d08706f8e884dbf762bcfc6ea.js","head.js":"head-0e76f317ff20568bdeeb63faa2aba07e.js","jquery-ui.js":"jquery-ui-9b83bb2951e6d03a2ff6810b5d324efe.js","jquery.js":"jquery-c8b0677586b29d1c1920a79f00f3a968.js","background/ld50-029-1600x1200_s1.jpg":"background/ld50-029-1600x1200_s1-f269e46ace2c9690a369745ccfd081dd.jpg","background/ld50-102-1600x1200_s1.jpg":"background/ld50-102-1600x1200_s1-0a07f384ef2fb59ec038a4b706e0dfd2.jpg","background/ld50-275-1600x1200_s1.jpg":"background/ld50-275-1600x1200_s1-707ddc8b7f5a0950757601d1e8c60dd1.jpg","bootstrap/glyphicons-halflings-white.png":"bootstrap/glyphicons-halflings-white-5a4ebf6392c45c5d8fb06ce668661c22.png"}}}
'''

**Comment by techpines** [comment]
Woot!  This is done!

https://github.com/techpines/asset-rack/blob/master/README.md#running-in-production-mode

**Comment by mwawrusch** [comment]
Good job,

but "Also, if you do happen to hit one of your static urls on the server,
then you will be redirected to the CDN."
is something that should be configurable, as it prevents the use of the
server as non amazon content origin source.

**Comment by techpines** [comment]
The way I implemented it, there would be no actual content on the server.  The server just has a map of non-hashed urls, to hashed urls so that it can reference assets correctly in an initial server side template.  So the config file just looks like this:

``` js
{"/app.js": "/app-2039rj023902309.js"}
```

Which means there is no way to serve the content.
